[build]
  command = "npm install && npm run build && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, access_token"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
